// <auto-generated />
using System;
using Coopera.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Coopera.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250921142234_iniciandoMigracion")]
    partial class iniciandoMigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Coopera.Models.Jugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PartidaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartidaId");

                    b.ToTable("Jugadores");
                });

            modelBuilder.Entity("Coopera.Models.MiniJuego", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdPartida")
                        .HasColumnType("int");

                    b.Property<int>("IdRecurso")
                        .HasColumnType("int");

                    b.Property<int>("JugadorId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tiempo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdPartida");

                    b.HasIndex("IdRecurso");

                    b.HasIndex("JugadorId");

                    b.ToTable("MiniJuegos");
                });

            modelBuilder.Entity("Coopera.Models.Partida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("HoraFinal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("MetaComida")
                        .HasColumnType("int");

                    b.Property<int>("MetaMadera")
                        .HasColumnType("int");

                    b.Property<int>("MetaPiedra")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Partidas");
                });

            modelBuilder.Entity("Coopera.Models.Recurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Nombre")
                        .HasColumnType("int");

                    b.Property<int>("PartidaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartidaId");

                    b.ToTable("Recursos");
                });

            modelBuilder.Entity("Coopera.Models.Jugador", b =>
                {
                    b.HasOne("Coopera.Models.Partida", "Partida")
                        .WithMany("Jugadores")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("Coopera.Models.MiniJuego", b =>
                {
                    b.HasOne("Coopera.Models.Partida", "Partida")
                        .WithMany("MiniJuegos")
                        .HasForeignKey("IdPartida")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Coopera.Models.Recurso", "Recursos")
                        .WithMany("MiniJuegos")
                        .HasForeignKey("IdRecurso")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Coopera.Models.Jugador", "Jugador")
                        .WithMany("MiniJuegos")
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Jugador");

                    b.Navigation("Partida");

                    b.Navigation("Recursos");
                });

            modelBuilder.Entity("Coopera.Models.Recurso", b =>
                {
                    b.HasOne("Coopera.Models.Partida", "Partida")
                        .WithMany("Recursos")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("Coopera.Models.Jugador", b =>
                {
                    b.Navigation("MiniJuegos");
                });

            modelBuilder.Entity("Coopera.Models.Partida", b =>
                {
                    b.Navigation("Jugadores");

                    b.Navigation("MiniJuegos");

                    b.Navigation("Recursos");
                });

            modelBuilder.Entity("Coopera.Models.Recurso", b =>
                {
                    b.Navigation("MiniJuegos");
                });
#pragma warning restore 612, 618
        }
    }
}
